---
title: "Assignment 2 Part 1 Support"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
```

(MIPS exercise 20.9) Let $X_{1},\ldots,X_{n}\overset{iid}{\sim}\text{Bernoulli}(p)$ and consider two estimators for $p$:
\[
T_{1} = \bar{X}, T_{2} = \text{min}(X_{1},\ldots,X_{n})
\]
The MSE for each estimator are
\[
\text{MSE}(T_{1}) = p(1-p)/n, \text{MSE}(T_{2}) = p^{n} - 2p^{n+1} + p^{2}
\]
Let's plot these as a function of $p$, for different values of $n$.

```{r plotmse}
# Define a function for both
MSE_T1 <- function(p,n) p*(1-p)/n
MSE_T2 <- function(p,n) p^n - 2*p^(n+1) + p^2

# Write a function to make the plot of p for fixed n
make_plot <- function(n) {
  tibble(x = c(0,1)) %>%
    ggplot(aes(x = x)) +
    theme_bw() +
    stat_function(fun = MSE_T1,args = list(n = n)) +
    stat_function(fun = MSE_T2,args = list(n = n),linetype = 'dashed') +
    labs(title = paste0("MSE for n = ",n),
         subtitle = "T1 (Solid) vs T2 (Dashed)",
         x = "p",
         y = "MSE"
    )
}

library(patchwork)
(make_plot(1) | make_plot(5)) / 
  (make_plot(10) | make_plot(20)) / 
  (make_plot(50) | make_plot(100)) 
```

